#
# LuaDist Travis-CI Hook
#

# We assume C build environments
language: C

# Run as is
script:
  - ./bootstrap

# List installed modules
after_script:
  - ./_install/bin/lua ./_install/lib/lua/luadist.lua list

# Only watch the master branch
branches:
  only:
    - master

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always
